name: devops_tools
on: push
jobs: 
  devops_tools_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Provide the list of DevOps Categories
        run: echo "$(cat devops_tools.txt)"
